services:
  api:
    container_name: "${SPRING_APPLICATION_NAME}"
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      SPRING_APPLICATION_NAME: "${SPRING_APPLICATION_NAME}"
      SPRING_PORT: "${SPRING_PORT}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}

  # snippet-asset-service
  asset-api:
    container_name: "parser-asset_service"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "${BUCKET_PORT}:8080"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_APP_NAME: "asset-service"
      NEW_RELIC_AGENT_ENABLED: "false"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "parser-azurite-snippets"
    hostname: azurite-snippets
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

  redis:
    container_name: "${REDIS_HOST}"
    image: redis:6-alpine
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

volumes:
  blob:
    external: false
