version: '3.8'

services:
  api:
    container_name: ${SPRING_APPLICATION_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}
    environment:
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
      SPRING_PORT: ${SPRING_PORT}
