version: '3.8'

services:
  api:
    container_name: "${SPRING_APPLICATION_NAME}"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}
  # snippet-asset-service
  asset-api:
    container_name: "asset_service"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "${BUCKET_PORT}:8080"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_APP_NAME: "asset-service"
      NEW_RELIC_AGENT_ENABLED: "false"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite-snippets"
    hostname: azurite-snippets
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace
volumes:
  blob:
    external: false
