name: "Continuous Integration"

on:
  push:
  pull_request:

jobs:
  call-build-workflow:
    name: Call build workflow
    run: ls -la
    uses: SnippetServices-Group4/Workflows/.github/workflows/build.yml@main
    with:
      env_file: '.env'
