name: "Continuous Integration"

on:
  push:
  pull_request:

jobs:
  call-build-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: ls -la

      - name: Call build workflow
        uses: SnippetServices-Group4/Workflows/.github/workflows/build.yml@main
        with:
          env_file: '.env'
