name: "Continuous Integration - Continuous Deployment"

on: [ "push", "pull_request" ]

jobs:
  call-build-workflow:
    name: Call build workflow
    uses: SnippetServices-Group4/Workflows/.github/workflows/build.yml@main
    secrets: inherit

  test-job-to-see-if-pull-req-works:
    needs: call-build-workflow
    if: github.event_name == 'pull_request'
    name: geda gedi

  call-publish-prod-images-workflow:
    needs: call-build-workflow
    if: github.event_name == 'pull_request' && github.base_ref == 'main' && github.event.pull_request.merged == true
    name: Call publish images workflow for production
    uses: SnippetServices-Group4/Workflows/.github/workflows/publish-images.yaml@main
    secrets: inherit
    inputs:
        workflow_file_path: "ghcr.io/snippetservices-group4/parsers:latest"

  call-publish-dev-images-workflow:
    needs: call-build-workflow
    if: github.event_name == 'pull_request' && github.base_ref == 'dev' && github.event.pull_request.merged == true
    name: Call publish images workflow for development
    uses: SnippetServices-Group4/Workflows/.github/workflows/publish-images.yaml@main
    secrets: inherit
    inputs:
        workflow_file_path: "ghcr.io/snippetservices-group4/parsers-dev:latest"
