name: "CD - Development"

on:
  pull_request:
    types: [closed]
    branches: [dev]

jobs:
  publish-dev-images-job:
    if: github.event.pull_request.merged == true
    name: Publish Docker Images for Development
    uses: SnippetServices-Group4/Workflows/.github/workflows/publish-images.yaml@main
    with:
      workflow_file_path: "ghcr.io/snippetservices-group4/parsers-dev:latest"
    secrets: inherit

  deploy-dev-vm-job:
    needs: publish-dev-images-job
    name: Deploy Images to Development VM
    uses: SnippetServices-Group4/Workflows/.github/workflows/deploy-images-vm.yaml@main
    with:
      environment: "development"
      service_name: "parser"
    secrets: inherit
