name: "CI/CD - Development"

# Trigger on pull request events and ensure only run when merged
on:
  pull_request:
    types: [closed]  # Triggers only when the pull request is closed (either merged or rejected)
    branches: [dev]

jobs:
  # Build job runs when a pull request is opened, updated, or reopened
  build-job:
    name: Build Job
    if: github.event.pull_request.merged == false
    uses: SnippetServices-Group4/Workflows/.github/workflows/build.yml@main
    secrets: inherit

  # Publish and deploy jobs run only when the pull request is merged into dev
  publish-dev-images-job:
    if: github.event.pull_request.merged == true
    name: Publish Docker Images for Development
    uses: SnippetServices-Group4/Workflows/.github/workflows/publish-images.yaml@main
    with:
      workflow_file_path: "ghcr.io/snippetservices-group4/parsers-dev:latest"
    secrets: inherit

  deploy-dev-vm-job:
    needs: publish-dev-images-job
    if: github.event.pull_request.merged == true
    name: Deploy Images to Development VM
    uses: SnippetServices-Group4/Workflows/.github/workflows/deploy-images-vm.yaml@main
    with:
      environment: "development"
      service_name: "parser"
    secrets: inherit
