name: "CI - Development"

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [dev]

jobs:
  build-job:
    name: Build Job
    uses: SnippetServices-Group4/Workflows/.github/workflows/build.yml@main
    secrets: inherit
